### ISSUE TITLE
Mention JENKINS-33925

### ISSUE THREAD

**Issue by jglick** [lesfurets/JenkinsPipelineUnit#11]
This repository seems to be addressing some or all of what has long been tracked as [JENKINS-33925](https://issues.jenkins-ci.org/browse/JENKINS-33925), so it would be a good idea to mention that somewhere in documentation.

**Comment by ozangunalp** [comment]
Hi @jglick, 

Thanks for the feedback. I am closing this issue, it is now mentioned in the readme.
