### ISSUE TITLE
Bad null argument handling

### ISSUE THREAD

**Issue by EQuincerot** [lesfurets/JenkinsPipelineUnit#19]
If you do so:
```
def myMethod(String foo) {
  return 'bar'
}

myMethod null
```
Then you get : `java.lang.IllegalArgumentException: wrong number of arguments`.
We need a way to make the difference between a null value of an argument and its non-existence.

**Comment by filipef9** [comment]
Hi,
I code a step:
```groovy
def call(Map vars) {
...
}
```
When I call:
```groovy
myStep(null)
```
Then I am still getting: `java.lang.IllegalArgumentException: wrong number of arguments`.
I've tested with versions 1.0 and 1.1.
