### ISSUE TITLE
How are environment variables injected?

### ISSUE THREAD

**Issue by ChastinaLi** [lesfurets/JenkinsPipelineUnit#20]
My Jenkinsfile uses environment variables like this:
```
username = env.USERNAME
```
I wonder how "env" can be mocked up in unit tests.
Currently, it gives an error:
```
Caused by: groovy.lang.MissingPropertyException: No such property: env for class: test
```

**Comment by davehunt** [comment]
I had the same question, then discovered:

```groovy
binding.setVariable('env', [KEY:"value"])
```

**Comment by EQuincerot** [comment]
Oh you are right, we forgot to explain that in the documentation.
We will fix that.

and @davehunt is totally right.

You can find an example here in the tests:
https://github.com/lesfurets/JenkinsPipelineUnit/blob/master/src/test/groovy/com/lesfurets/jenkins/TestExampleJob.groovy#L17

**Comment by ChastinaLi** [comment]
Thanks. ❤️
