### ISSUE TITLE
How to register methods without arguments

### ISSUE THREAD

**Issue by ChastinaLi** [lesfurets/JenkinsPipelineUnit#23]
I've been stuck on trying to register a method that has no arguments. 
I get nullPointerException trying to do it the way below:
`getHelper().registerAllowedMethod(method(methodName, null), { c -> "${methodName} executed successfully" })`
How do I use registerAllowedMethod to mock methods without arguments?
🙏 🙏 🙏  Any help is greatly appreciated 🙏 🙏 🙏

**Comment by EQuincerot** [comment]
Hi ChastinaLi,

The basic way to register a method without argument is:
> helper.registerAllowedMethod('myMethod', [], { println 'Executing My Method' })

Use an empty list (`[]`) rather than `null` in the second parameter of `registerAllowedMethod`.

Does that solve your problem?

**Comment by ChastinaLi** [comment]
👍 👍 👍 
Any plan to do a new release soon? 😉

**Comment by EQuincerot** [comment]
There is no official schedule for the next release.
However the syntax suggested below is already available with the latest release.

The changes I did today are some documentation improvements and syntactic sugar to write it even simpler.

**Comment by ChastinaLi** [comment]
Thanks ❤️
