### ISSUE TITLE
How to test DSL vars?

### ISSUE THREAD

**Issue by ewhauser** [lesfurets/JenkinsPipelineUnit#25]
This library is great and really useful for testing Jenkins Pipelines. I'm using it to test our shared library for Jenkins and having some success. I'm setting up the tests with this:

```groovy
  @Rule
  public TemporaryFolder scriptsFolder = new TemporaryFolder()

  @Before
  void setup() {
    setUp()
    FileUtils.copyDirectory(new File('.'), scriptsFolder.newFolder('sharedlib@master'))
    def library = library()
            .name('sharedlib')
            .retriever(localSource(scriptsFolder.root.absolutePath))
            .targetPath(scriptsFolder.root.absolutePath)
            .defaultVersion("master")
            .allowOverride(true)
            .implicit(false)
            .build()
    helper.registerSharedLibrary(library)
  }
```

When testing a simple var, this works fine:

```groovy
// vars/gitCommit.groovy
import com.sharedlib.Scm

String call() {
  env.GIT_COMMIT ?: Scm.current().commit()
}
```

```groovy
  def SHA = '96cd94a34dda6ce6a1ad51eeb4ea68769be45c00'

  @Test
  void testFindsInEnvironmentVariable() throws Exception {
    binding.setVariable('env', ['GIT_COMMIT' : SHA])
    loadScript("src/main/jenkins/pythonProject.jenkins")
    assertTrue(helper.callStack.findAll { call ->
        call.methodName == "sh"
    }.any { call ->
        callArgsToString(call).contains("echo $SHA")
    })
  }
```

However, if I try to bind a method to var that uses a DSL method, I can't seem to get it to locate the variable:

```groovy
// vars/testPython.groovy
def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  def sources = config.sources
  node {
    sh "nosetests --someflags ${sources}"
  }
}
```

```groovy
  @Test
  void testPythonBlock() throws Exception {
    helper.registerAllowedMethod("node", [Map, Closure], null)
    loadScript("src/main/jenkins/pythonProject.jenkins")
  }
```

```
groovy.lang.MissingMethodException: No signature of method: testPython.node() is applicable for argument types: (testPython$_call_closure1) values: [testPython$_call_closure1@27adc16e]
Possible solutions: use([Ljava.lang.Object;), notify(), wait(), run(), run(), dump()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:81)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at testPython.call(testPython.groovy:22)
```

How can I bind these methods to vars?

Thanks.

**Comment by ozangunalp** [comment]
Hi @ewhauser, 

It is pretty strange. There is a test in the project which applies exactly your use case. You can see them here : 

Test class : 
https://github.com/lesfurets/JenkinsPipelineUnit/blob/master/src/test/groovy/com/lesfurets/jenkins/TestSharedLibrary.groovy

Test shared lib var : 
https://github.com/lesfurets/JenkinsPipelineUnit/blob/master/src/test/resources/libs/commons%40feature/vars/helloMessage.groovy

Test script :
https://github.com/lesfurets/JenkinsPipelineUnit/blob/master/src/test/jenkins/job/library/libraryJob_feature.jenkins

Could you give more context on how you use the var in `pythonProject.jenkins` ?

**Comment by ewhauser** [comment]
@ozangunalp: Thanks for looking at this. I eventually figured it out (and yes it was strange).

In my `build.gradle` file, I was putting my vars on the classpath so IntelliJ would load it as a source folder.

```groovy
sourceSets {
    main {
        java {
            srcDirs = ['src/mainjava', 'vars/']
        }
    }
}
```
For whatever reason, that was causing the issue with the classloading.

**Comment by BernalCarlos** [comment]
Removing the `vars` folder will break IntelliJ autocompletion. I think the source of the problem should be pursued.

**Comment by seflue** [comment]
I ran into the same problem but like @BernalCarlos I think that the problem is not resolved because of the broken autocompletion in IntelliJ when `vars` is not part of the main source set.
