### ISSUE TITLE
Testing Library Method that Accesses Build Variable

### ISSUE THREAD

**Issue by juwi** [lesfurets/JenkinsPipelineUnit#27]
I have a Pipeline Library that accesses the build number of the current build. Something along the lines of the following method:

`def getCurrentBuildNumber() {
    def output = env.getEnvironment().containsKey("BUILD_NUMBER") ? new String("$env.BUILD_NUMBER") : new String("")
    return output
}`

This works fine in a Jenkins Jobs, however I cannot figure out how to test this kind of thing. The problem seems to be related to env. 

A simple test case setting the variable with

`helper.setGlobalVars(new Binding(["BUILD_NUMBER":123]))`

for the method above yields a groovy.lang.MissingPropertyException No such property: env when I call the above method. I assume that in an actual Jenkins instance this functionality is provided by an injected EnvActionImpl class, but I understand too little of Jenkins internals to actually know whats going on.

Is this a bug/missing feature or am I doing it wrong?

**Comment by meena432** [comment]
For the above issue you need to bind like this:
 binding.setVariable('env', [
                    BUILD_NUMBER                           : '1'

            ])
Hope this useful.

**Comment by juwi** [comment]
That did the trick. Thank you!
