### ISSUE TITLE
MissingMethodException: No signature of method

### ISSUE THREAD

**Issue by roderickrandolph** [lesfurets/JenkinsPipelineUnit#28]
In our jenkins shared library project we commonly reuse or invoke functions from other functions in the same library. I'm attempting to write unit tests for this scenario and keep hitting the `MissingMethodException` exception.

Here's a simplified example:

```groovy

// file: vars/sayHello.groovy
def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  echo 'say Hello!'
}

// file: vars/greetings.groovy
def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  sayHello {}
}

// file: Jenkinsfile
@Library('sharedlib') _

node {
  greetings {}
}
```

When executing a test it throws:

```
groovy.lang.MissingMethodException: No signature of method: greetings.sayHello() is applicable for argument types: (greetings$_call_closure1) values: [greetings$_call_closure1@3407e97e]
```

Is this a limitation of the framework or am I doing something wrong?

**Comment by ozangunalp** [comment]
Hi @roderickrandolph, 

I modified an existing test and I cannot reproduce the case you are describing. 
Could you look at the mentioned commit to see how it is different from your usage ?

Thanks.

**Comment by roderickrandolph** [comment]
Thank you @ozangunalp for the quick response and helping me find my problem. It turned out to be a user error on my part. I had set additional `sourceSets` paths in my Gradle `build.gradle` script and one of them affected the classpath. This test started working as soon as I discovered what I did wrong. Thank you again and sorry for the false alarm.

Also, thank you for creating this framework, it's awesome!!

**Comment by roderickrandolph** [comment]
@ozangunalp sorry, I'm back. Below is the test case I should have shared originally. 

```groovy
// file: vars/sayHello.groovy
def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  echo 'say Hello!'
}

def hello(name) {
  echo "Hello, ${name}"
}
```

```groovy
// file: vars/greetings.groovy
def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  sayHello.hello("World!")
}
```

```groovy
// file: Jenkinsfile
greetings {}
```

When `greetings {}`  runs and tries to call `sayHello.hello("World!")` it throws this exception: `groovy.lang.MissingPropertyException: No such property: sayHello for class: greetings`.

I believe this was the point where I originally started to muck around with the classpath so that `sayHello.hello()` would be recognized but then that caused other issues including the initial issue above. Is the `call()` method the only method supported at this time or is there a workaround to support other methods too?

One way around it is to explicitly load `sayHello.groovy` into `greetings.groovy`:

```groovy
// file: vars/greetings.groovy
def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  def sayHello = load 'vars/sayHello.groovy'
  sayHello.hello("World!")
}
```

But this won't work when the script is executed on Jenkins because in the Jenkins context `load` will look for a file named `vars/sayHello.groovy` in the project's job workspace (which won't exist) vs the shared library workspace. Thoughts?

Thank you!

**Comment by ozangunalp** [comment]
Hi again @roderickrandolph,

I just verified and indeed it is a bug. Hopefully it is an easy fix. 

I'll try to push the fix to the snapshot release today, so that you can confirm it. 
As for the definitive release, I am planning to do it during this week as soon as I find some time.

Btw even though the framework has some limitations, It is never preferable to change your pipeline scripts so that you can test them.

Thanks for the heads up and please don't hesitate to report any other issue.
