### ISSUE TITLE
Not able to bind the scm in util files

### ISSUE THREAD

**Issue by meena432** [lesfurets/JenkinsPipelineUnit#29]
Not able to bind the variables like scm inside main file calling other util files sample code
def call() {
    String stage_pkg_prefix="com.wellsfargo.sharedlib.stages."
    def mandatoryStages= ["Checkout","Build"]
    def buildNumber, pipelineProperties, appProperties
    def stageStartTime = new Date()
    //def scmUtil = new ScmUtils()
    def scmUtil = new ScmUtils()
    //def utils = load "./loadLibraryResource.groovy"
   // def scripta = load("./loadLibraryResource.groovy");
    //pipelineProperties=utils.call("resources/common/pipelineProperties.groovy");
    def lr=new loadLibraryResource()
    def root="/pipelineProperties.groovy"
    try{
        node{
            pipelineProperties = "abc"
            stage("Checkout"){
                node{
                    println "Executing Stage: Checkout"
                    def appURL
                    appURL = scmUtil.getBranchURL()
                    println "Executing Stage: appurl${appURL}"
                    println "Branch URL: ${appURL} ${pwd()}"
                    if(scmUtil.isGitScm()){
                        scmUtil.gitCheckOut(pipelineProperties.getRepoCredentialsID(), appURL,"develop");
                        println "Git Clone Completed"
                    }else{
                        scmUtil.subVersionCheckOut(pipelineProperties.getRepoCredentialsID(), appURL)
                    }
                }
            }
here scmUtil file having scm command which I am not able to bind it.

**Comment by ozangunalp** [comment]
I'm closing this issue because of lack of clarity.
