### ISSUE TITLE
Cannot register pipeline method names that are also Groovy keywords

### ISSUE THREAD

**Issue by macg33zr** [lesfurets/JenkinsPipelineUnit#34]
I cannot find a way to register a pipeline method that is also a Groovy keyword.

For example:
`registerAllowedMethod("sleep", [Integer.class], { println "SLEEP!!!"})`

Then in my Jenkins pipeline under tests I have this to sleep 30 seconds:
`sleep 30`

The interceptors do not seem to pick it up, my registered closure is not called. 

I found it as I was analysing my pipeline call-stacks while generating regressions. I think in the unit tests it is just doing a Groovy sleep(30) for 30 milliseconds so it is pretty harmless. Just wondered if there is a way to do this or if it is a limitation we have with this technique? Normally, anything is possible with Groovy so may be there is a way.

**Comment by ozangunalp** [comment]
Hi @macg33zr, 

Indeed it is possible to fix it but only if you use the CPS versions of the framework (cf. https://github.com/lesfurets/JenkinsPipelineUnit#note-on-cps). 

For reference it is a bit related to this issue : 
https://github.com/spockframework/spock/issues/88

I pushed the fix, you can test it with the snapshot version.

Thanks.
