### ISSUE TITLE
Cannot invoke method if the script file name contains hyphens

### ISSUE THREAD

**Issue by vitalii-vitrenko** [lesfurets/JenkinsPipelineUnit#35]
For example, we have a scripts with the name `pipeline-script.Jenkinsfile`
And it contains the following code
```
def hello() {
    println "hello"
}
hello()
```
If we invoke `loadScript('pipeline-script.Jenkinsfile')` in tests we will get `java.lang.ClassFormatError: Illegal class name "pipeline-script$hello" in class file pipeline-script$hello`
However if we remove a hyphen in the script name(`pipelinescript.Jenkinsfile`) it will run without exceptions.

Jenkins pipeline plugin allows using scripts with any characters. So if our scripts contains hyphens we have to rename them for testing.

**Comment by ozangunalp** [comment]
Hi @vitalii-vitrenko, 

I cannot reproduce this issue. I am thinking that it is linked to [GROOVY-7670](https://issues.apache.org/jira/browse/GROOVY-7670). 

Are you testing on Windows ?

**Comment by vitalii-vitrenko** [comment]
Hi @ozangunalp 
Yes, it seems this is a groovy issue.
I tried both Windows 10 and Ubuntu 16.04 and got `ClassFormatError` on both.

**Comment by ozangunalp** [comment]
I added an appveyor build to the project but it seems to be passing the tests.
I suggest you to test out different combinations of JDK/Groovy. 
It seems to pass on Groovy 2.4.5/2.4.6 on jdk1.8.0_77 Mac OS

**Comment by ozangunalp** [comment]
@vitalii-vitrenko any news on this issue ?

**Comment by vitalii-vitrenko** [comment]
I tried several version of groovy and Mac OS but this issue still persist. But if it is related to [GROOVY-7670.](https://issues.apache.org/jira/browse/GROOVY-7670) and not to JenkinsPipelineUnit I don't mind if you close this ticket.
