### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by bluesliverx** [lesfurets/JenkinsPipelineUnit#36]
I'm curious why only Java 8 is supported here?  Is there anything in particular that prevents you compiling with Java 8 but using Java 7 bytecode so that tests can be written in 7 or 8?

**Comment by vitalii-vitrenko** [comment]
Why do you think that only Java 7 is supported?
From the [README.md](https://github.com/lesfurets/JenkinsPipelineUnit/blob/master/README.md)

> You can write your tests in Groovy or Java 8, using the test framework you prefer.

**Comment by bluesliverx** [comment]
Doh, it was a typo in the first sentence.  I'm curious why only Java *8* is supported here... Updated

**Comment by ozangunalp** [comment]
@vitalii-vitrenko thanks for clarifying 

@bluesliverx
The framework uses some Java function/stream APIs so as of now it will require a Java 8 SDK. 

Plus I included Function/Consumer variants of the `registerAllowedMethod` method to enable using the framework in Java (not only Groovy). 

It would be possible to rewrite those portions in pure Groovy and replace function/consumers with callback interfaces and compile the sources with Java 7 compatibility, but I don't think we'll go for that, cause it is 2017 and Java 7 is EOL.

**Comment by bluesliverx** [comment]
Ok, makes sense, just wanted to check to see if it was an easy thing :) Thanks!
