### ISSUE TITLE
Cannot printCallStack for a parallel step with a complex map

### ISSUE THREAD

**Issue by headcrabmeat** [lesfurets/JenkinsPipelineUnit#41]
I've suggested a test with a complex map like. 
```
s = [s1:[name:"action1-name", body:{
      node() {
        sh 'sleep 3'
        error 'message'
      }
    }], s2:[name: "action2-name", body:{
        node() {
            sh 'sleep 4'
        }
    }]]

    parallel(
      "$s.s1.name":s.s1.body,
      "$s.s2.name":s.s2.body,
      failFast:true
    )
```
It seems that the script itself works fine, however I get the exception on `printCallStack()`
``
java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
```

**Comment by headcrabmeat** [comment]
#40

**Comment by ozangunalp** [comment]
We had this issue a while ago and if i remember correctly we had a fix. It is clearly a regression. I'll merge your PR and prepare a fix.

**Comment by headcrabmeat** [comment]
Hey, I can try to use bisect, maybe I can found the commit wit that fix

**Comment by ozangunalp** [comment]
No, that's ok. It is a problem with Groovy.  

You can reproduce it by 
```
    @Test
    void name() throws Exception {
        String s1 = '1234'
        def m = [
            "$s1":1,
            aKey:2
        ]
        assertTrue(m instanceof Map)
        m.sort()
    }
```

I removed the unnecessary sort.
