### ISSUE TITLE
Can I access the real "dir", "sh" etc. in my pipeline?

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [lesfurets/JenkinsPipelineUnit#42]
Hey,

I see that many pipeline steps are mocked by functions doing nothing (for example dir, sh etc.),

Now I want to test a groovy library which uses these steps, and I want it to really execute them.

How should I do that? Can I somehow access existing implementations of these commands that really do something? Do I have to implement them myself?

Thanks!
Nathan

**Comment by ozangunalp** [comment]
Hi @RudolfVonKrugstein, 

Sorry for the late response. 

The testing framework has no knowledge of real implementations of these steps. 

So you should write your own mock implementations that execute steps. But it'll be laborious, 
there are a plethora of kinds of steps. If you want to mock a small subset, I guess it is manageable but you should mock also the workspace (execution directory), scm steps, sh, dir etc.

**Comment by RudolfVonKrugstein** [comment]
Ok, thanks. For now I will mock according to my needs, which leaves most things unmocked :-).

**Comment by ozangunalp** [comment]
Great! Is there a reason why you cannot use version 1.0 of this framework ?

**Comment by SpencerMalone** [comment]
It's mostly that the goals are different. If you want to unit test, this
repo is A+, but I realized that I was looking to test the interaction
between my shared library / pipelines and my version of jenkins + plugins.
Most of my real world issues have been related to syntax changing after
plugin updates, not so much logical issues in my units.

**Comment by ozangunalp** [comment]
Indeed I looked more into it. You do not use the unit testing at all. 
The JenkinsRule approach is totally viable to test if a shared library is compatible with a given version of jenkins and plugins.

The startup times you are getting should be higher though. 
It would be great to find some middle ground and get both the practicality of this fw with the high reliability of JenkinsRule.
