### ISSUE TITLE
Issue in mocking a script in shared library folder

### ISSUE THREAD

**Issue by mioyn** [lesfurets/JenkinsPipelineUnit#49]
I have the following script files aScript.groovy and bScript.groovy both are in shared library folder, these scripts will be called from a jenkinsFile in the project folder; it executed. well I need to mock bScript.groovy.
how can i mock this, i tried using `helper.registerAllowedMethod("bScript", [], null)` but its not mocking bScript, I also tried using metaclass `bScript.metaClass.static.call = {return 'bar'}` but its giving me `groovy.lang.MissingPropertyException: No such property: bScript for class: aScriptSpec`

**aScript.groovy**

     def call(){
        return bScript()
    }

 **bScript.groovy**

      def call(){
         return "bar"
     }

**Comment by bguerin** [comment]
```
        getBinding().setVariable("bScript", new Object() {
            public void call() {
                // your mocked behaviour
            }
        });
```

**Comment by mioyn** [comment]
it didnt worked it is executing bScript()

**Comment by headcrabmeat** [comment]
I think your  repository has a wrong layout. 
I believe `aScript` and `bScript` should be stored in `var[s]` not in `var` folder

**Comment by mioyn** [comment]
sorry that was my typo mistake ,actually both are in the vars folder..
**my project structure,**
app
     \--build
               \--classes
                             \--test
                                     \--aScriptSpec.class
               \--resources
                             \--test
                                     \--lib
                                              \--commons@master
                                                                                \--vars
                                                                                          \-- aScript.groovy
                                                                                          |--bScript.groovy
     |--src/test/groovy
                                 \--aScriptSpec.groovy
     |--vars
               \--aScript.groovy
               |--bScript.groovy
     |--build.gradle
     \--Jenkinsfile

**Comment by headcrabmeat** [comment]
Yep, I've just reproduced that

```
@Test
  void mock_bscript() throws Exception {
    helper.registerAllowedMethod("bScript", [String.class], {c -> 'foo'})
    def script = loadScript("template/pipeline/template.groovy")
    helper.registerAllowedMethod("bScript", [String.class], {c -> 'ololo'})
    script.someMethod()
    printCallStack()
  }
```

**Comment by headcrabmeat** [comment]
All in all I think the impact of this issue is really low. If you test your `pipelines` and `libs` separately then you can define any pipelines to load your lib with a proper way to make it able to test it

**Comment by mioyn** [comment]
When i do the gradle build it create a shared library structure and copy all the resource to that folder. am not sure why its not mocking bScript and executing the call method

**Comment by mioyn** [comment]
thanks @headcrabmeat  @bguerin
